platform :ios, '9.0'

target 'MoyaTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MoyaTest
  pod 'Moya', '11.0.2'
  pod 'Alamofire', '4.7.2'
  pod 'CHLMVP'
  pod 'mLayout'
  pod 'SVProgressHUD', '2.2.5'

  target 'MoyaTestTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Moya', '11.0.2'
    pod 'Alamofire', '4.7.2'
    pod 'CHLMVP'
  end

end
